// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin-login" | "/admin/categories" | "/admin/looks" | "/admin/looks/[id]/edit" | "/admin/looks/new" | "/admin/orders" | "/admin/orders/[id]" | "/admin/products" | "/admin/products/[id]/edit" | "/admin/products/new" | "/checkout" | "/checkout/success" | "/contact" | "/favoris" | "/home-v2" | "/looks-test" | "/notre-histoire" | "/nouveautes" | "/panier" | "/produit/[slug]" | "/shop" | "/shop/[gender]/[category]" | "/shop/femme" | "/shop/homme"
type AppRouteHandlerRoutes = "/api/admin/auth/login" | "/api/admin/auth/logout" | "/api/admin/categories" | "/api/admin/categories/[id]" | "/api/admin/looks" | "/api/admin/looks/[id]" | "/api/admin/orders" | "/api/admin/orders/[id]" | "/api/admin/products" | "/api/admin/products/[id]" | "/api/admin/stats" | "/api/admin/upload" | "/api/contact" | "/api/products/by-ids"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/favoris" | "/panier"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin-login": {}
  "/admin/categories": {}
  "/admin/looks": {}
  "/admin/looks/[id]/edit": { "id": string; }
  "/admin/looks/new": {}
  "/admin/orders": {}
  "/admin/orders/[id]": { "id": string; }
  "/admin/products": {}
  "/admin/products/[id]/edit": { "id": string; }
  "/admin/products/new": {}
  "/api/admin/auth/login": {}
  "/api/admin/auth/logout": {}
  "/api/admin/categories": {}
  "/api/admin/categories/[id]": { "id": string; }
  "/api/admin/looks": {}
  "/api/admin/looks/[id]": { "id": string; }
  "/api/admin/orders": {}
  "/api/admin/orders/[id]": { "id": string; }
  "/api/admin/products": {}
  "/api/admin/products/[id]": { "id": string; }
  "/api/admin/stats": {}
  "/api/admin/upload": {}
  "/api/contact": {}
  "/api/products/by-ids": {}
  "/checkout": {}
  "/checkout/success": {}
  "/contact": {}
  "/favoris": {}
  "/home-v2": {}
  "/looks-test": {}
  "/notre-histoire": {}
  "/nouveautes": {}
  "/panier": {}
  "/produit/[slug]": { "slug": string; }
  "/shop": {}
  "/shop/[gender]/[category]": { "gender": string; "category": string; }
  "/shop/femme": {}
  "/shop/homme": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/favoris": never
  "/panier": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
